name: Build and deploy ASP.Net Core app to Azure Web App - Invenshopfy-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install EF Tools
        run: |
          cd ./InvenShopfy.Api
          dotnet tool install --global dotnet-ef

      - name: Set connection string for Azure PostgreSQL
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: |
          cd ./InvenShopfy.Api
          echo "Using connection string from secrets"
          dotnet ef database update --connection "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"

      - name: Debug environment variables
        run: |
          echo "FrontendUrl: ${{ secrets.FRONTENDURL }}"
          echo "BackendUrl: ${{ secrets.BACKENDURL }}"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish -c Release -o ${{ github.workspace }}/published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/published

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Invenshopfy-backend'
          slot-name: 'Production'
          package: ${{ github.workspace }}/published
        env:
          ASPNETCORE_ENVIRONMENT: "Production"
          FrontendUrl: ${{ secrets.FRONTENDURL }}
          BackendUrl: ${{ secrets.BACKENDURL }}
